### ISSUE TITLE
What is the maximum size of a file that can be uploaded and downloaded? 

### ISSUE THREAD

**Issue by omimo** [michaelnixon/mm-file-support#13]
It has to be specified in the create new track page

**Comment by omimo** [comment]
I could not upload a file which is 1.6 GB.

**Comment by michaelnixon** [comment]
You can set the max size using Paperclip (the gem used to handle file uploads). This is not currently done, however.
You can set the max size using Apache. I don't believe this is currently done.
You can set the max size using the user account on linux. I haven't looked into this at all.

From my research, Apache has an unavoidable 2gb file size limit, which may be the practical upper limit. The resource I checked specified this for 32-bit Apache, which may not be applicable, so you should confirm it.

At any rate, you're looking for the upper limit on what Apache/the OS can handle, since we're not throttling it anywhere else, AFAIK.

----- Original Message -----

**Comment by omimo** [comment]
Thanks Michael for the through response. 

@subirranjan1, can you please make sure this information is provided to the users on the upload page and they are given a proper error message if the file is larger that the limit?

**Comment by subirranjan1** [comment]
@omimo , Sure. 

@omimo  Are we on a conclusion what is the upper limit?

**Comment by omimo** [comment]
@subirranjan1, can you check the documentation for the limit?
