### ISSUE TITLE
Change the Contact page to follow the proposed design

### ISSUE THREAD

**Issue by omimo** [michaelnixon/mm-file-support#29]

**Comment by subirranjan1** [comment]
@amkass  @omimo  Please comment for design modifications. Awaiting comment on below mentioned pages. Will be working on other pages after your comments.
1. Project Browser
2. Track Browser
3. About
4. Contact

**Comment by omimo** [comment]
Thanks for the modifications Subir! The Contacts page looks good. Here are my comments:
1. The "An SFU Moving Stories Project", the breadcrumbs, "Contacts", and the "MoDa" in the logo should be aligned. 
2. There should be more space between the subtitle "An SFU Moving Stories Project" and the line separator. As in the PDF.

Meanwhile, I had a quick look at other pages the about page and: 
1. I believe in the help page, the sections should be designed in an accordion style way. With lines as separators. 
2. The links' color and font style should be changed according to the design. @amkass, how should the links be styled when hovered? I think we decided on red. 
3. The space between the "User Data" and "Programmatic Access" should be bigger.

**Comment by subirranjan1** [comment]
@omimo : Please find my comments following the dashes
1. The "An SFU Moving Stories Project", the breadcrumbs, "Contacts", and the "MoDa" in the logo should be aligned.  --- This is done.
1. There should be more space between the subtitle "An SFU Moving Stories Project" and the line separator. As in the PDF.
   --Looks to me that the main content goes below half of the screen because of giving more space. However I have implemented it as per the pdf and your request but feel free to let me know in case you or @amkass need to modify it. 

Meanwhile, I had a quick look at other pages the about page and: 
1. I believe in the help page, the sections should be designed in an accordion style way. With lines as separators. -- done
2. The links' color and font style should be changed according to the design. @amkass, how should the links be styled when hovered? I think we decided on red.

**Comment by omimo** [comment]
It looks fine.
